In [1]:
import pandas as pd

In [16]:
HealthCode = pd.read_csv("050326_HealthCodePrograms.csv")
HealthCode

,DCID,Permit Number,Program Name,Facility Type,Program Type,Street Address,Borough,Zip Code,Phone Number,Child Age Range,Children Allowed in Care,Administer Medication,BIN,BBL,Community Board,Council District,Census Tract,NTA Code,Latitude,Longitude
0,DC1000,2165.0,BILLY MARTIN CHILD DEVELOPMENT CENTER,GCC,PRESCHOOL,333 CLASSON AVENUE,BROOKLYN,11205,(718) 857-5630,2 YEARS - 5 YEARS,70,No,3321871.0,3.019380e+09,303.0,36.0,23300.0,BK75,40.689761,-73.960169
1,DC1021,4135.0,NUESTROS NINOS DAY CAR 1,GCC,PRESCHOOL,384 SOUTH 4 STREET,BROOKLYN,11211,(718) 963-1555,2 YEARS - 5 YEARS,142,No,3063507.0,3.024510e+09,301.0,34.0,52700.0,BK73,40.708077,-73.952515
2,DC10244,6700.0,BIRCH FAMILY SERVICES,GCC,PRESCHOOL,10-24 49 AVENUE,QUEENS,11101,(718) 786-1104,2 YEARS - 5 YEARS,114,Yes,4436607.0,4.000420e+09,402.0,26.0,700.0,QN31,40.743273,-73.953205
3,DC1030,6767.0,"PHIPPS NEIGHBORHOODS, INC.",GCC,PRESCHOOL,921 EAST 180 STREET,BRONX,10460,(917) 243-7145,2 YEARS - 5 YEARS,54,No,2114117.0,2.031280e+09,206.0,15.0,36300.0,BX17,40.844492,-73.881472
4,DC10454,3050.0,THE CHILD DEVELOPMENT CENTER OF KINGSBOROUGH C...,GCC,PRESCHOOL,1915 ORIENTAL BOULEVARD,BROOKLYN,11235,(718) 368-5439,2 YEARS - 5 YEARS,38,No,3326936.0,3.087600e+09,315.0,48.0,61600.0,BK17,40.578490,-73.935321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2732,DC34781,105498.0,ABR Prospect LLC,GCC,PRESCHOOL,243 ST. MARKS AVENUE,BROOKLYN,11238,(718) 684-7981,2 YEARS - 5 YEARS,72,No,3028206.0,3.011450e+09,308.0,35.0,20500.0,BK64,40.678318,-73.967452
2733,DC44468,106852.0,CONGREGATION ML,GCC,INFANT TODDLER,4419 12 AVENUE,BROOKLYN,11219,(718) 438-1353,0 YEARS - 2 YEARS,68,No,3426871.0,3.056100e+09,312.0,44.0,22200.0,BK88,40.638989,-73.991561
2734,DC2000,6497.0,"BIRCH FAMILY SERVICES,INC.",GCC,PRESCHOOL,1880 WATSON AVENUE,BRONX,10472,(718) 828-9400,2 YEARS - 5 YEARS,180,No,2023653.0,2.037320e+09,209.0,18.0,4400.0,BX55,40.828300,-73.861558
2735,DC20798,8128.0,KISSENA CHERRY DAYCARE INC.,GCC,PRESCHOOL,140-26 CHERRY AVE.,QUEENS,11355,(718) 886-2889,2 YEARS - 5 YEARS,100,No,4535115.0,4.051928e+09,407.0,20.0,85900.0,QN22,40.754116,-73.822414
2736,DC349,4476.0,"THE NEW LIFE CHILD DEVELOPMENT CENTER, INC",GCC,PRESCHOOL,295 WOODBINE STREET,BROOKLYN,11237,(718) 821-3432,2 YEARS - 5 YEARS,105,No,3076869.0,3.033620e+09,304.0,37.0,43500.0,BK77,40.696405,-73.912941

In [17]:
Desert = pd.read_csv("Desert Map_082025.csv")
Desert

,GEOID,GEOID2,CTName,Geography,County,REDC,ChLT5Yrs,Ch5_9Yrs,Ch10_14Yrs,TotalPop,...,AnyITPSlots,GT49ChU5yr,ChU5PerSl,DesCat0123,REDCDesPerc,CT_Title,DesLevel1,DesLevel2,REDCDesLev,IncLT200.1
0,36001000100,1400000US36001000100,Census Tract 1,Census Tract 1; Albany County; New York,Albany,Capital Region,180,71,155,2156,...,N,Y,NaN,3,63.8%,"Census Tract 1, Albany County, Capital Region ...",Desert-High,No Slots & >=50 children/CT,63.8% of CTs in region are deserts,48%
1,36001000201,1400000US36001000201,Census Tract 2.01,Census Tract 2.01; Albany County; New York,Albany,Capital Region,94,52,193,2519,...,Y,Y,0.28,0,63.8%,"Census Tract 2.01, Albany County, Capital Regi...",Not a Desert,0.28 children/slot,63.8% of CTs in region are deserts,61%
2,36001000202,1400000US36001000202,Census Tract 2.02,Census Tract 2.02; Albany County; New York,Albany,Capital Region,251,244,130,2436,...,Y,Y,5.98,1,63.8%,"Census Tract 2.02, Albany County, Capital Regi...",Desert-Low,5.98 children/slot,63.8% of CTs in region are deserts,54%
3,36001000301,1400000US36001000301,Census Tract 3.01,Census Tract 3.01; Albany County; New York,Albany,Capital Region,98,51,167,2378,...,Y,Y,1.85,0,63.8%,"Census Tract 3.01, Albany County, Capital Regi...",Not a Desert,1.85 children/slot,63.8% of CTs in region are deserts,64%
4,36001000302,1400000US36001000302,Census Tract 3.02,Census Tract 3.02; Albany County; New York,Albany,Capital Region,380,74,73,3273,...,Y,Y,31.67,2,63.8%,"Census Tract 3.02, Albany County, Capital Regi...",Desert-Medium,31.67 children/slot,63.8% of CTs in region are deserts,9%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5391,36123150301,1400000US36123150301,Census Tract 1503.01,Census Tract 1503.01; Yates County; New York,Yates,Finger Lakes,102,186,250,2907,...,Y,Y,5.67,1,64.5%,"Census Tract 1503.01, Yates County, Finger Lak...",Desert-Low,5.67 children/slot,64.5% of CTs in region are deserts,21%
5392,36123150302,1400000US36123150302,Census Tract 1503.02,Census Tract 1503.02; Yates County; New York,Yates,Finger Lakes,132,168,61,2066,...,N,Y,NaN,3,64.5%,"Census Tract 1503.02, Yates County, Finger Lak...",Desert-High,No Slots & >=50 children/CT,64.5% of CTs in region are deserts,29%
5393,36123150400,1400000US36123150400,Census Tract 1504,Census Tract 1504; Yates County; New York,Yates,Finger Lakes,181,183,173,3798,...,Y,Y,1.55,0,64.5%,"Census Tract 1504, Yates County, Finger Lakes ...",Not a Desert,1.55 children/slot,64.5% of CTs in region are deserts,18%
5394,36123150501,1400000US36123150501,Census Tract 1505.01,Census Tract 1505.01; Yates County; New York,Yates,Finger Lakes,136,118,114,2040,...,Y,Y,27.20,2,64.5%,"Census Tract 1505.01, Yates County, Finger Lak...",Desert-Medium,27.2 children/slot,64.5% of CTs in region are deserts,18%
5395,36123150502,1400000US36123150502,Census Tract 1505.02,Census Tract 1505.02; Yates County; New York,Yates,Finger Lakes,203,124,216,2687,...,Y,Y,33.83,2,64.5%,"Census Tract 1505.02, Yates County, Finger Lak...",Desert-Medium,33.83 children/slot,64.5% of CTs in region are deserts,24%

In [18]:
#if missing value, can return no match found
import numpy as np

In [19]:
#can call websites or APIs
import requests
#can limit the time between API requests, so I don't get blocked by a site
import time

In [26]:
#map each borough (in health codes) to each county (in deserts)

#dictionary borough to counties
borough_to_county = {"MANHATTAN": "New York",
    "BROOKLYN": "Kings",
    "QUEENS": "Queens",
    "BRONX": "Bronx",
    "STATEN ISLAND": "Richmond"}

#now map every county to a borough. So county is now added to the end of this table
HealthCode["County"] = HealthCode["Borough"].map(borough_to_county)
HealthCode[["Borough", "County"]].sample(10)

        Borough    County
553    BROOKLYN     Kings
118    BROOKLYN     Kings
774    BROOKLYN     Kings
1413   BROOKLYN     Kings
2520     QUEENS    Queens
2683   BROOKLYN     Kings
256   MANHATTAN  New York
1391     QUEENS    Queens
2508  MANHATTAN  New York
257   MANHATTAN  New York

In [25]:
print(HealthCode.columns)

Index(['DCID', 'Permit Number', 'Program Name', 'Facility Type',
       'Program Type', 'Street Address', 'Borough', 'Zip Code', 'Phone Number',
       'Child Age Range', 'Children Allowed in Care', 'Administer Medication',
       'BIN', 'BBL', 'Community Board', 'Council District', 'Census Tract',
       'NTA Code', 'Latitude', 'Longitude', 'County'],
      dtype='str')

In [28]:
#create new code for census tract in HealthCode
HealthCode["tract_code"] = (
    HealthCode["Census Tract"]
    .astype("Int64")
    .astype(str)
    .str.zfill(6))
HealthCode["tract_code"]

0       023300
1       052700
2       000700
3       036300
4       061600
         ...
2732    020500
2733    022200
2734    004400
2735    085900
2736    043500
Name: tract_code, Length: 2737, dtype: str

In [31]:
#convert these tract_code values to stings
HealthCode["tract_code"] = (HealthCode["Census Tract"].astype("string"))

#manually add census tracts for blanks using https://censusreporter.org/locate/
manual_tracts = {"100A ALDRICH STREET": "046205",
    "16-01 150 STREET": "001029",
    "2351 ADAM CLAYTON POWELL JR BOULEVARD": "000228",
    "472 ATLANTIC AVENUE": "000039",
    "2750 FREDERICK DOUGLASS BOULEVARD": "000234",
    "2600 ADAM CLAYTON POWELL JR BOULEVARD": "000236"}

HealthCode["tract_code"] = HealthCode["tract_code"].fillna(
    HealthCode["Street Address"].map(manual_tracts))

#verify
HealthCode[HealthCode["Street Address"].isin(manual_tracts.keys())][
    ["Street Address", "Census Tract", "tract_code"]
]

                             Street Address  Census Tract tract_code
735                     100A ALDRICH STREET           NaN     046205
1003                       16-01 150 STREET           NaN     001029
1548  2351 ADAM CLAYTON POWELL JR BOULEVARD           NaN     000228
2119                    472 ATLANTIC AVENUE           NaN     000039
2120                    472 ATLANTIC AVENUE           NaN     000039
2324      2750 FREDERICK DOUGLASS BOULEVARD           NaN     000234
2500  2600 ADAM CLAYTON POWELL JR BOULEVARD           NaN     000236
2501  2600 ADAM CLAYTON POWELL JR BOULEVARD           NaN     000236

In [35]:
#Do I have duplicate addresses for the same preschool?
duplicates = HealthCode[
    HealthCode.duplicated(subset=["Street Address"], keep=False)]
duplicates = duplicates.sort_values(by="Street Address")
duplicates

,DCID,Permit Number,Program Name,Facility Type,Program Type,Street Address,Borough,Zip Code,Phone Number,Child Age Range,...,BIN,BBL,Community Board,Council District,Census Tract,NTA Code,Latitude,Longitude,County,tract_code
1183,DC2822,6809.0,"IMAGINE EARLY LEARNING CENTERS,LLC",GCC,INFANT TODDLER,1 JAMAICA CENTER PLAZA,QUEENS,11432,(718) 557-5520,0 YEARS - 2 YEARS,...,4451048.0,4.100970e+09,412.0,27.0,24000.0,QN61,40.703266,-73.800405,Queens,24000.0
797,DC2244,6810.0,IMAGINE ELC @ Jamaica Kids,GCC,PRESCHOOL,1 JAMAICA CENTER PLAZA,QUEENS,11432,(718) 557-5520,2 YEARS - 5 YEARS,...,4451048.0,4.100970e+09,412.0,27.0,24000.0,QN61,40.703266,-73.800405,Queens,24000.0
1638,DC36793,104617.0,NYU LANGONE HEALTH CHILD CARE CENTER,GCC,INFANT TODDLER,1 PARK AVENUE,MANHATTAN,10016,(646) 754-7004,0 YEARS - 2 YEARS,...,1018472.0,1.008888e+09,105.0,2.0,7200.0,MN20,40.746062,-73.982071,New York,7200.0
1637,DC36791,104614.0,NYU LANGONE HEALTH CHILD CARE CENTER,GCC,PRESCHOOL,1 PARK AVENUE,MANHATTAN,10016,(646) 754-7004,2 YEARS - 5 YEARS,...,1018472.0,1.008888e+09,105.0,2.0,7200.0,MN20,40.746062,-73.982071,New York,7200.0
681,DC21253,8251.0,"CENTRAL PARK MONTESSORI, INC.",GCC,INFANT TODDLER,1 WEST 91ST STREET,MANHATTAN,10024,(212) 595-2000,0 YEARS - 2 YEARS,...,1031625.0,1.012050e+09,107.0,6.0,17700.0,MN12,40.788528,-73.967130,New York,17700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,DC10582,6198.0,GOOD SAMARITAN FULTON DAY CARE CENTER-PRESCHOOL,GCC,PRESCHOOL,992 GATES AVENUE,BROOKLYN,11221,(718) 443-6463,2 YEARS - 5 YEARS,...,3039623.0,3.014800e+09,303.0,41.0,37500.0,BK35,40.689292,-73.923685,Kings,37500.0
567,DC19685,8016.0,THE JOY OF LEARNING DAY CARE CENTER,GCC,PRESCHOOL,992 GATES AVENUE,BROOKLYN,11221,(718) 443-6463,NO DATA,...,3039623.0,3.014800e+09,303.0,41.0,37500.0,BK35,40.689292,-73.923685,Kings,37500.0
225,DC14162,6199.0,GOOD SAMARITAN FULTON DAY CARE CENTER - INFANT...,GCC,INFANT TODDLER,992 GATES AVENUE,BROOKLYN,11221,(718) 443-6463,0 YEARS - 2 YEARS,...,3039623.0,3.014800e+09,303.0,41.0,37500.0,BK35,40.689292,-73.923685,Kings,37500.0
2336,DC43804,106630.0,Winny's Happy Apple Place LLC,GCC,INFANT TODDLER,992 LORIMER STREET,BROOKLYN,11222,(929) 734-5292,0 YEARS - 2 YEARS,...,3065591.0,3.026198e+09,301.0,33.0,56100.0,BK76,40.725632,-73.952863,Kings,56100.0
2337,DC43805,106631.0,Winny's Happy Apple Place LLC,GCC,PRESCHOOL,992 LORIMER STREET,BROOKLYN,11222,(929) 734-5292,2 YEARS - 5 YEARS,...,3065591.0,3.026198e+09,301.0,33.0,56100.0,BK76,40.725632,-73.952863,Kings,56100.0

Street Address
992 GATES AVENUE        4
1859 RICHMOND AVENUE    3
712 BEDFORD AVENUE      3
3480 THIRD AVENUE       3
76 LORRAINE STREET      3
                       ..
1-55 BORDEN  AVENUE     2
186-01 73 AVENUE        2
77-42 164 STREET        2
85 JAY STREET           2
844 BEDFORD AVENUE      2
Name: count, Length: 458, dtype: int64